site_name: NoEngineer Blog
site_url:  https://noengineer.xyz
site_description: Engineering projects, modifications, and technical documentation
site_author: Jesse Smith

# Repository info
repo_name: yourusername/noengineerblog
repo_url: https://github.com/yourusername/noengineerblog
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

# Navigation
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md

# Extensions
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      categories_allowed:
        - Engineering
        - Hardware
        - Software
        - Art
        - Coffee
        - Modifications
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 10

# Extra CSS/JS (optional)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername

# Custom domain (add after domain setup)
# extra:
#   custom_domain: noenginer.xyz