site_name: NoEngineer Blog
site_url:  https://noengineer.xyz
site_description: Engineering projects, modifications, and technical documentation
site_author: Jesse Smith

# Repository info
repo_name: jessefordcolter/noengineer
repo_url: https://github.com/jessefordcolter/NoEngineer

# Configuration
docs_dir: docs
site_dir: site

# Theme
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list

# Navigation
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md


# Plugins
plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      posr_url_format: {slug}